-- AlterTable
ALTER TABLE "Customers" ALTER COLUMN "cep" SET DATA TYPE BIGINT,
ALTER COLUMN "phone" SET DATA TYPE BIGINT,
ALTER COLUMN "cpf" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "phone" SET DATA TYPE BIGINT,
ALTER COLUMN "cpf" SET DATA TYPE BIGINT;
